### ISSUE TITLE
Dibscheckout not defined. 

### ISSUE THREAD

**Issue by martinowren** [krokedil/dibs-easy-for-woocommerce#126]
![image](https://user-images.githubusercontent.com/22822433/107373475-ddbb6400-6ae6-11eb-90c1-a88626aa81eb.png)

Hi! One of my clients are getting this error with the newest version of the plugin.
Please help me give you the correct info you need to debug this. 

Thanks!

**Comment by NiklasHogefjord** [comment]
Hi @martinowren,

This isn't a general bug in the plugin. It's probably related to some configuration. If you have further questions and can't solve the problem we are happy to help you via support@krokedil.se.
