### ISSUE TITLE
Checkout fields are persistent

### ISSUE THREAD

**Issue by klingberg** [krokedil/dibs-easy-for-woocommerce#131]
Hi!

I have an issue with checkout fields being persistent. For instance, if I add an order note and then switch to pay on delivery and type something else in the order note and then switch back to Dibs payment again the order note will still be what I typed in the first place. I have the same issue with custom checkout fields which is my real concern. What I would like to do is to add a field with a default value depending on what the user has in his cart (using the woocommerce_checkout_fields hook). This works fine as long as the user does not alter the content in his cart because the field will still have the initial value when returning to the checkout page.

Wordpress: 5.7
Woocommerce: 5.1.0
Nets Easy for WooCommerce: 1.22.0

**Comment by NiklasHogefjord** [comment]
Hi @klingberg,
Sorry for the late reply.

I have gone through the code now and have an update/fix in the Develop branch. The changes means that we don't save and re-populate the order note field (and other extra checkout fields) when switching back to Nets Easy. This code was part of an older checkout flow in the plugin and was no longer necessary.

It will be released in the next version that will be published within a couple of days.

**Comment by NiklasHogefjord** [comment]
Hi again,
The new version with the fix is now released. I'm closing this issue now. Please feel. free to re-open it if it doesn't solve your problem.

**Comment by klingberg** [comment]
Tested the new release and can confirm that everything is now working as expected.

Thank you!!

**Comment by NiklasHogefjord** [comment]
Great, thanks!
