### ISSUE TITLE
Not possible to refund orders payed with Swish?

### ISSUE THREAD

**Issue by orjhor** [krokedil/dibs-easy-for-woocommerce#132]
Hi,

It seems **charge_id** is not saved for orders with payment type **A2A / account to account**, and therefore trying to refund these orders results in the error message: 
_Nets Easy order could not be refunded. Missing Charge id._

More specifically, this code (line 60 in class-dibs-post-checkout.php):

`
if ( 'A2A' === $payment_type ) {
	// This is a account to account purchase (like Swish). No activation is needed/possible.
	$dibs_payment_method = get_post_meta( $order_id, 'dibs_payment_method', true );
	/* Translators: Nets payment method for the order. */
	$wc_order->add_order_note( sprintf( __( 'No charge needed in Nets system since %s is a account to account payment.', 'dibs-easy-for-woocommerce' ), $dibs_payment_method ) );
	return;
}
`

 ..makes the function return before the following code is executed:

`update_post_meta( $order_id, '_dibs_charge_id', $request->chargeId ); `

Is this by design? If A2A/Swish orders cannot be refunded from Woocommerce, then why can they be refunded manually in the [Nets portal](https://portal.dibspayment.eu)?

Thanks!

**Comment by NiklasHogefjord** [comment]
Hu @orjhor,

Charge ID should be saved even for Swish order. However, it might be that the customer doesn't navigate back correctly to the checkout/browser after finalizing the payment in the Swish app (if doing the purchase via mobile phone). If that's the case it seems like the charge id isn't saved correctly to the order.

I will look into this and release a fix for the issue.

**Comment by NiklasHogefjord** [comment]
A new version is now released that hopefully solves your issue. Please get back to us again if you have further questions.

**Comment by orjhor** [comment]
Hi again,
This seems to still be an issue, even after the fix referred to above. The the only place **_dibs_charge_id** is written to the database is (still) in _class-dibs-post-checkout.php_, and as I mentioned in my initial post above, that code will never execute for A2A orders (like Swish):


Notice the return below (line 65 in _class-dibs-post-checkout.php):
```
if ( 'A2A' === $payment_type ) {
				// This is a account to account purchase (like Swish). No activation is needed/possible.
				$dibs_payment_method = get_post_meta( $order_id, 'dibs_payment_method', true );
				/* Translators: Nets payment method for the order. */
				$wc_order->add_order_note( sprintf( __( 'No charge needed in Nets system since %s is a account to account payment.', 'dibs-easy-for-woocommerce' ), $dibs_payment_method ) );
				return;
			}
```

But **_dibs_charge_id** is saved _after_ A2A orders have returned, (line 84 in _class-dibs-post-checkout.php):

```
			$request = new DIBS_Requests_Activate_Order( $order_id );
			$request = json_decode( $request->request() );

			// Error handling.
			if ( null !== $request ) {
				if ( isset( $request->chargeId ) ) { // Payment success.
					// Translators: Nets Charge ID.
					$wc_order->add_order_note( sprintf( __( 'Payment charged in Nets Easy with charge ID %s', 'dibs-easy-for-woocommerce' ), $request->chargeId ) ); // phpcs:ignore

					update_post_meta( $order_id, '_dibs_charge_id', $request->chargeId ); // phpcs:ignore
```








>  it might be that the customer doesn't navigate back correctly to the checkout/browser after finalizing the payment in the Swish app (if doing the purchase via mobile phone). 

I can see that this also affects orders made from desktop clients (Windows), so my bet is still on the issue described above - that in fact **_dibs_charge_id** is never saved for Swish orders.
