### ISSUE TITLE
iPhone / Safari - sessionStorage.getItem( 'DIBSRedirectUrl' ) empty when returning from payment gateway. 

### ISSUE THREAD

**Issue by Razko90** [krokedil/dibs-easy-for-woocommerce#150]
When initiating an payment on iPhone safari you get redirected to Vipps after you complete the payment in vipps you get sent back to safari but the checkout page opens in a new tab therefor the sessionStorage is empty and the customer never sees the order-received / thankyou page.

https://github.com/krokedil/dibs-easy-for-woocommerce/blob/dd5b34cd8aa140c8c76d4e147fa11b7c7a96e15e/assets/js/checkout.js#L198

sessionStorage.getItem( 'DIBSRedirectUrl');
= null.

**Comment by Razko90** [comment]
Quick fix change from sessionStorage to localStorage. 

But this is not an good fix, and will break if the customer initiates the payment in an in app browser (eg instragram) or not the "default" browser after the vipps payment you will be redirected to the default browser. 

https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api.md#please-note
https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api.md#recommendations-regarding-handling-redirects

**Comment by NiklasHogefjord** [comment]
Thanks for the report. We will discuss this internally and see if we can find a solution that works also for purchases started via app browsers.

**Comment by Provi-Web** [comment]
> Thanks for the report. We will discuss this internally and see if we can find a solution that works also for purchases started via app browsers.

Did you discuss this internally yet? @NiklasHogefjord

**Comment by NiklasHogefjord** [comment]
Hi @Provi-Web,
Yes, we have discussed it. We will try to find a solution for this during August. I will get back in this issue as soon as we have a fix ready.

**Comment by Provi-Web** [comment]
Hey @NiklasHogefjord 

Just checking in to get an update here - any news for when a fix can be expected?

**Comment by Modii** [comment]
We are having the same problem on our site.
Mobilepay wont redirect to the thank you pay once the payment is complete.

Would love to have this fixed ASAP! 
Looking forward to your reply @NiklasHogefjord and thanks for the efforts :D

**Comment by NarfArf** [comment]
Facing a similar issue with MobilePay on customer redirects here as well. 

Scenario sounds identical to above. We tried testing the "fix" suggested at the top and can confirm it fixes the issue as long as we're in the default browser. 

Would be happy to help test a potential fix if there's a "beta" version available. :) @NiklasHogefjord

**Comment by Provi-Web** [comment]
Hey Niklas,

Any update/status for this @NiklasHogefjord ?
We have about a dozen clients all experiencing the same issue every day, where the customer is not sure if their order was placed, due to them not being redirected to the thank you page when paying with MobilePay.

If you are able to, we would really appreciate any sort of timeline / estimated release for this fix (Even a rough estimate)

**Comment by NiklasHogefjord** [comment]
I'm so sorry for the delay @Provi-Web. I'm looking into this now and I'm talking to Nets how we can solve this in the best way. My aim is to have a release ready next week.

**Comment by Provi-Web** [comment]
Hey @NiklasHogefjord 

That sounds great, we are looking forward to the release.

Do you have any update on the release date or when to expect it?

**Comment by NiklasHogefjord** [comment]
Finally @Provi-Web, this should now be fixed. Sorry for the long wait. Version 2.2.0 includes better support for this. I'm closing this issue, but feel free to re-open it again if you still experience problems.
