### ISSUE TITLE
Stripping white space in phone numbers norway.

### ISSUE THREAD

**Issue by Razko90** [krokedil/dibs-easy-for-woocommerce#151]
In norway many customers write their phonenumbers as: 

https://en.wikipedia.org/wiki/Telephone_numbers_in_Norway
9xx xx xxx (Sometimes formatted as 9x xx xx xx)

https://github.com/krokedil/dibs-easy-for-woocommerce/blob/dd5b34cd8aa140c8c76d4e147fa11b7c7a96e15e/classes/requests/helpers/class-dibs-requests-get-checkout.php#L174

This will not strip whitepaces from that format.

**Comment by NiklasHogefjord** [comment]
Hi,
We will look into this and add a fix in the next release.

**Comment by NiklasHogefjord** [comment]
Sorry for the late reply. I'm closing this since it was fixed in version 1.25.1.
