### ISSUE TITLE
Broken with redis-cache

### ISSUE THREAD

**Issue by oxyc** [krokedil/dibs-easy-for-woocommerce#169]
The same issue was reported for you KCO plugin https://github.com/krokedil/klarna-checkout-for-woocommerce/issues/204. Currently your plugin is broken if the site uses a persistent object cache.

I've already sent a PR with the same fix as you committed to the klarna plugin https://github.com/krokedil/dibs-easy-for-woocommerce/pull/156

**Comment by montazarr** [comment]
This has now been merged (see #156 ).

Thank you!
