### ISSUE TITLE
Support order-pay

### ISSUE THREAD

**Issue by oxyc** [krokedil/dibs-easy-for-woocommerce#170]
Are there any plans to support "order-pay"?

Would you accept a PR if we sponsored the work? If not, could we pay you to implement it?

**Comment by NiklasHogefjord** [comment]
Hi @oxyc,
The plugin should already have support for order pay. 

If _Embedded checkout flow_ is selected in plugin settings, the _Redirect (to hosted payment window) flow_ will be used when it's a matter of a "order-pay" purchase. Is that not working for you? Or do you still want it to be an embedded checkout flow experience for the customer?
