### ISSUE TITLE
Rounding issue in check order totals function

### ISSUE THREAD

**Issue by Kristian-Andersson** [krokedil/dibs-easy-for-woocommerce#89]
Rounding issue when comparing DIBS total with Woocommerce total.

https://github.com/krokedil/dibs-easy-for-woocommerce/blob/03da51ea61d6393e1907d80864b74a694c7926fa/classes/class-dibs-api-callbacks.php#L170

**Comment by NiklasHogefjord** [comment]
Probably a good idea to format id similar to how we do it when we send it to DIBS: https://github.com/krokedil/dibs-easy-for-woocommerce/blob/3a39360b8667462d0a56e0203fdc509adaf7c18d/classes/requests/helpers/class-dibs-requests-get-order.php#L25
